services:
  database:
    container_name: 'database'
    image: postgres:17
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin
      POSTGRES_DB: collaborize
    ports:
      - '5432:5432' # Ensure this line is present
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    environment:
      DATABASE_URL: postgres://dbadmin:dbadmin@database:5432/collaborize
    ports:
      - '3000:3000'
    networks:
      - web

  reverse-proxy:
    container_name: 'reverse-proxy'
    image: caddy:latest
    environment:
      APP_URL: host.docker.internal:3000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '80:80' # HTTPS
      - '443:443' # HTTPS
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
