export const userDescriptions = [
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Software Engineer',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h2',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🚀 Passionate about building scalable, efficient, and maintainable software solutions.',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '💡 Focused on problem-solving, clean code, and continuous learning.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Tech Stack:',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'JavaScript, TypeScript, Python',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Node.js, React, Next.js',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'PostgreSQL, Redis, MongoDB',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Interests:',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Distributed Systems',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Performance Optimization',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Open-Source Contributions',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🔗 ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'GitHub',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' | ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'LinkedIn',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Frontend Developer',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h1',
        },
        {
          children: [
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: '🎨 UI/UX Focused | ⚡ React Enthusiast | 🛠️ JavaScript Lover',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Crafting intuitive, performant, and accessible web applications with a strong emphasis on user experience.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Tech Stack',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h3',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'React, Next.js, Vue.js',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Tailwind CSS, Styled Components',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'TypeScript, JavaScript',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🎯 ',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Passions:',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Micro Frontends',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Motion UI & Animations',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Design Systems',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🌍 ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Portfolio',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' • 🏢 ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'GitHub',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Backend Developer',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h2',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🔧 Architecting scalable and reliable backend systems.',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '📡 APIs, databases, and cloud services are my playground.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Specialties',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h4',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '✔️ Microservices & Serverless Architectures',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '✔️ High-Performance Database Design',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '✔️ Secure & Scalable REST/GraphQL APIs',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Languages & Tools:',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Go, Rust, Python',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'PostgreSQL, MySQL, Redis',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Kubernetes, Docker, Terraform',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🚀 ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Projects',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' | 🛠️ ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'GitHub',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Full Stack Developer',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h3',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🔹 Versatile developer bridging the gap between frontend and backend.',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🔹 Passionate about developer experience, performance, and maintainability.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Tech Stack',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h4',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '📌 ',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Frontend:',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' React, Next.js, Svelte, TypeScript',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '📌 ',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Backend:',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' Node.js, Express, GraphQL, Prisma',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '📌 ',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Infra:',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' Docker, CI/CD, AWS, Vercel',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '📜 Blog: ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Read Here',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' | 💻 Open Source: ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'GitHub',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'DevOps & Cloud Engineer',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h2',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '⚙️ ',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Optimizing deployment pipelines and automating infrastructure.',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🏗️ ',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Building resilient cloud architectures.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Expertise in AWS, GCP, Kubernetes, and Terraform',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'CI/CD pipelines for efficient software delivery',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Scripting with Bash, Python, and Go',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🔗 Explore more: ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Portfolio',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' | ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'GitHub',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Game Developer 🎮',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h2',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🕹️ Creating immersive gaming experiences with cutting-edge technology.',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🚀 Focused on gameplay programming, physics, and AI.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Toolset',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h3',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Engines:',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' Unity, Unreal Engine',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Languages:',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' C++, C#, Python',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Specialties:',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' Procedural Generation, VR/AR, Game AI',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🔗 ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Portfolio',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' | 🏆 ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'GitHub',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Machine Learning Engineer 🤖',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h1',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Developing intelligent systems that turn data into actionable insights.',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '📊 ',
              type: 'text',
              version: 1,
            },
            {
              detail: 0,
              format: 1,
              mode: 'normal',
              style: '',
              text: 'Deep Learning, NLP, and Computer Vision enthusiast.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Expertise',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h3',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '✔️ TensorFlow, PyTorch, Scikit-Learn',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '✔️ Model Optimization & Interpretability',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '✔️ Big Data & Cloud ML: AWS, GCP, Databricks',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🔗 Blog: ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'AI Insights',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' | 🛠️ GitHub: ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Repos',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
  {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'UI/UX Designer 🎨',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h2',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '✨ Designing beautiful and accessible user experiences.',
              type: 'text',
              version: 1,
            },
            {
              type: 'linebreak',
              version: 1,
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '📐 Specializing in human-centered design and interaction principles.',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Skills & Tools',
              type: 'text',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'heading',
          version: 1,
          tag: 'h3',
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Design:',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' Figma, Adobe XD, Sketch',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Prototyping:',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' Framer, InVision',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 2,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'User Research & Testing',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: 'start',
              indent: 0,
              type: 'listitem',
              version: 1,
              value: 3,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          type: 'list',
          version: 1,
          listType: 'bullet',
          start: 1,
          tag: 'ul',
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: '🌎 Portfolio: ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'See Work',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
            {
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: ' | 🎨 Dribbble: ',
              type: 'text',
              version: 1,
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Designs',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              type: 'link',
              version: 1,
              rel: null,
              target: null,
              title: null,
              url: 'https://markdownlivepreview.com/#',
            },
          ],
          direction: 'ltr',
          format: 'start',
          indent: 0,
          type: 'paragraph',
          version: 1,
          textFormat: 0,
          textStyle: '',
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      type: 'root',
      version: 1,
    },
  },
]
