name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Check Linting
        run: pnpm lint

      - name: Check Styling
        run: pnpm style
